---
apiVersion: v1
kind: Service
metadata:
  name: custom-backend
  namespace: ingress-nginx
  labels:
    app.kubernetes.io/name: custom-backend
    app.kubernetes.io/part-of: ingress-nginx
spec:
  selector:
    app.kubernetes.io/name: custom-backend
    app.kubernetes.io/part-of: ingress-nginx
  ports:
  - port: 80
    targetPort: 8080
    name: http
---
apiVersion: apps/v1beta2
kind: Deployment
apiVersion: apps/v1beta2
metadata:
  name: custom-backend
  namespace: ingress-nginx
  labels:
    app.kubernetes.io/name: custom-backend
    app.kubernetes.io/part-of: ingress-nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: custom-backend
      app.kubernetes.io/part-of: ingress-nginx
  template:
    metadata:
      labels:
        app.kubernetes.io/name: custom-backend
        app.kubernetes.io/part-of: ingress-nginx
    spec:
      containers:
      - name: nginx-error-server
        image: gcr.io/dd-decaf-cfbf6/nginx-ingress-default-backend:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
        - name: FLASK_APP
          value: main.py
        - name: FLASK_ENV
          value: production
        command: ["flask", "run", "-h", "0.0.0.0", "-p", "8080"]
