version: "3.2"
services:
  web:
    build: .
    image: gcr.io/dd-decaf-cfbf6/nginx-ingress-default-backend:latest
    ports:
      - "8080:8080"
    environment:
      - FLASK_APP=main.py
      - FLASK_ENV=production
    command: flask run -h 0.0.0.0 -p 8080
